### ISSUE TITLE
Functional errors

### ISSUE THREAD

**Issue by GuillaumeDespaux** [algosup/2024-2025-project-1-fpga-team-2#6]
There is a list of all the typos and words that can be changed for improve your document : 

- "Equipement" → Equipment (Typo) 8, 71
- "comparaison" → comparison (Typo) 47
- "desgins" → designs (Typo) 47, 229
- "mecanics" → mechanics (Typo) 51
- "horizontaly" → horizontally (Typo) 55
- "inversly" → inversely (Typo) 55
- "hit an obstacle" → hits an obstacle (Grammatical error) 55
- "fall in the water" → falls into the water (Grammar and preposition) 59
- "complet a level" → complete a level (Typo) 61
- "turtules" → turtles (Typo) 66
- "programed" → programmed (Typo) 75
- "choosen" → chosen (Typo) 94
- "his way" → its way (Wrong pronoun for raccoon) 94
- "Traffic: The vehicules"** → vehicles (Typo) 108
- "garbage tucks" → garbage trucks (Typo) 108
- "vehicules" → vehicles (Typo) 108
- "reached trash gives +10000" → reaching a trash gives +10,000 points (Typo and formatting) 181
- "realised" → achieved (Better word choice) 189
- "had external hardware" → add external hardware (Typo) 232
- "Jumping animation" → A jumping animation (Clarity) 235

Also you can make the words written into the Glossary as anchor to see directly what the word means during the review.

**Comment by ghost** [comment]
Is it possible to have the lines for typos please
