### ISSUE TITLE
Readme bugs

### ISSUE THREAD

**Issue by Enonome** [algosup/2024-2025-project-1-fpga-team-2#8]
In the README.md file, the picture of LinkedIn and GitHub don't appear for everyone. Also, the pictures of Vianney, Habi and Lucas are missing. Moreover, the Vianney's, Alexandre's and my links for GitHub AND LinkedIn are lacking. Finally, Habi's link for GitHub is missing and yours for LinkedIn.

**Comment by Mattstar64** [comment]
Pull request done by the program manager
